### ISSUE TITLE
Get rid of Universal::isa

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/ConfigReader-Simple#1]

**Comment by openstrike** [comment]
I must be missing something here because I can find no reference to UNIVERSAL::isa anywhere in the repo other than the Changes file which suggests it has already been removed.

Is this a non-issue? Or what am I not seeing?

**Comment by briandfoy** [comment]
It looks like this was fixed in 66f7e881aab7a4708ae3144869bcf0d59d7a9fe6. Thanks for looking though!
